# This rule is not used by the project kubernetesstudyoperatorsdk itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.osuk8s.site.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetesstudyoperatorsdk
    app.kubernetes.io/managed-by: kustomize
  name: simplegolangapp-editor-role
rules:
- apiGroups:
  - apps.osuk8s.site
  resources:
  - simplegolangapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.osuk8s.site
  resources:
  - simplegolangapps/status
  verbs:
  - get
