# This rule is not used by the project kubernetesstudyoperatorsdk itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.osuk8s.site resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetesstudyoperatorsdk
    app.kubernetes.io/managed-by: kustomize
  name: simplegolangapp-viewer-role
rules:
- apiGroups:
  - apps.osuk8s.site
  resources:
  - simplegolangapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.osuk8s.site
  resources:
  - simplegolangapps/status
  verbs:
  - get
