# This rule is not used by the project visitors-helm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.osuk8s.site.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: visitors-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: visitorsapp-admin-role
rules:
- apiGroups:
  - apps.osuk8s.site
  resources:
  - visitorsapps
  verbs:
  - '*'
- apiGroups:
  - apps.osuk8s.site
  resources:
  - visitorsapps/status
  verbs:
  - get
