apiVersion: apps.osuk8s.site/v1alpha1
kind: SimpleGolangApp
metadata:
  labels:
    app.kubernetes.io/name: kubernetesstudyoperatorsdk
    app.kubernetes.io/managed-by: kustomize
  name: simplegolangapp-sample
spec:
  # TODO(user): Add fields here
