apiVersion: apps.osuk8s.site/v1alpha1
kind: SimpleGolangApp
metadata:
  labels:
    app.kubernetes.io/name: kubernetesstudyoperatorsdk
    app.kubernetes.io/managed-by: kustomize
  name: simple-golang
spec:
  # TODO(user): Add fields here
  image: zooeymoon1989/simple-golang:latest
  replicas: 1
  port: 80
